// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using melkikerapostgrescrud.Data;

#nullable disable

namespace melkikerapostgrescrud.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("userVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("melkikerapostgrescrud.Entities.ArretsLigne", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("code_insee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom_commune")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("operatorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pointgeoId")
                        .HasColumnType("integer");

                    b.Property<string>("route_long_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("shortname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stop_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stop_lat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stop_lon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stop_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("pointgeoId");

                    b.ToTable("ArretsLigne");
                });

            modelBuilder.Entity("melkikerapostgrescrud.Entities.Pointgeo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("lat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("lon")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PointGeos");
                });

            modelBuilder.Entity("melkikerapostgrescrud.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("melkikerapostgrescrud.Entities.ArretsLigne", b =>
                {
                    b.HasOne("melkikerapostgrescrud.Entities.Pointgeo", "pointgeo")
                        .WithMany()
                        .HasForeignKey("pointgeoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pointgeo");
                });
#pragma warning restore 612, 618
        }
    }
}
